<?php
/**
 * @file
 * Code for the os2web_hrmanager_job feature.
 */

include_once 'os2web_hrmanager_job.features.inc';


/**
 * Return our custom formats.
 *
 * @return
 * info about custom formats
 */
function os2web_hrmanager_job_date_formats_get_names() {
  static $names = array('short_date' => 'd-m-Y');
  return $names;
}

/**
 * Implements hook_date_formats().
 */
function os2web_hrmanager_job_date_formats() {
  $formats = array();
  $names = os2web_hrmanager_job_date_formats_get_names();

  foreach ($names as $key => $value) {
    $formats[] = array(
      'type' => $key,
      'format' => $value,
      'locales' => array(),
    );
  }

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function os2web_hrmanager_job_date_format_types() {
  $types = array();
  $names = os2web_hrmanager_job_date_formats_get_names();

  foreach ($names as $key => $value) {
    $types[$key] = t($key);
  }

  return $types;
}

/**
 * Implements hook_flush_caches().
 */
function os2web_hrmanager_job_flush_caches() {
  $names = os2web_hrmanager_job_date_formats_get_names();
  foreach ($names as $key => $value) {
    $formats = system_get_date_formats($key);
    variable_set('date_format_' . $key, $value);

    foreach ($formats as $format) {
      if (!empty($format['dfid'])) {
        system_date_format_delete($format['dfid']);
      }
    }
  }
}

/**
 * Cleans the HTML.
 *
 * @param $html
 *  HTML to clean.
 *
 * @return string
 *  Cleaned HTML.
 */
function os2web_hrmanager_job_clean_up_html($html) {
  $html = check_markup($html, 'hr_manager_job_html');
  // Removes empty tags.

  $html = preg_replace('/<((\S+)[^<\/>]*)>((\s|&nbsp;)*)<\/\1>/uimsU', '', $html);
  $html = preg_replace('/&lt;\?xml[^>]+\/&gt;/i', '', $html);
  // Removes empty <p> tags.
  $html = str_replace("&nbsp;", '', $html);
  $html = preg_replace("/<p[^>]*>(\s|&nbsp;| )*<\/p>/i", '', $html);
  // Do first paragraph as <h2>.
  if (preg_match('%(<p[^>]*>){0,1}(.+?)(<br>|</p>|<br />)$%im', $html, $regs)) {
    if (strlen(strip_tags($regs[2])) < 200) {
      $html = preg_replace('%(<p[^>]*>){0,1}(.+?)(<br>|</p>|<br />)$%im', '$1<h2>' . $regs[2] . '</h2>$3', $html, 1);
    }
  }

  return $html;
}

/**
 * Implements hook_feeds_after_parse().
 *
 * Body field must be full html , but we must cut html inline styles while importing.
 * This is what this function does.)))
 */
function os2web_hrmanager_job_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {
  $config = $source->importer()->getConfig();
  if ($config['processor']['config']['bundle'] == 'os2web_hr_manager_job') {
    foreach ($result->items as &$item) {
      $item['xpathparser:1'] = os2web_hrmanager_job_clean_up_html($item['xpathparser:1']);
    }
  }
}